# Arquivo para deploy do CESS em produção.
# VaultID - Soluções em criptografia e identidade.
# 02/01/2019
version: "3"
services:
  cess:
    image: harbor.lab.vaultid.com.br/cess/cess:latest
    depends_on:
      - redis
    restart: always
    user: "33"
    environment:
      - "debug=false"
      - "vaultCloudUrl=https://apicloudid.vaultid.com.br"
      - "vaultCloudClientId=false"
      - "vaultCloudClientSecret=false"
      - "actTSA=http://act1.vaultid.com.br:9318"
      - "version=v1.0.7"
      # Se necessário, edite apenas as variávies abaixo: #
      - "cessUrl=http://localhost:8080"
      - "APACHE_SSL=false"
      # Configurar abaixo caso utilize HSM local.
      #- "signatureAdapter=DinamoAdapter"
      #- "hsmIp=IP_HSM"
      #- "hsmPort=HSM_PORT"
    ports:
      # Definir a PORTA_EXTERNA TCP pela qual o container será exposto na rede.
      - PORTA_EXTERNA:8080
#    volumes:
#      - path_crt:/etc/apache2/cert/cert.pem
#      - path_key:/etc/apache2/cert/cert.key
    networks:
      - nw-cess
  redis:
    image: "healthcheck/redis:alpine"
    restart: always
    networks:
      - nw-cess
networks:
  nw-cess:
    driver: bridge
    ipam:
      driver: default
